service: instagram-notion-integration

frameworkVersion: '3'

useDotenv: true

provider:
  name: aws
  runtime: nodejs22.x
  region: ap-northeast-1
  timeout: 60
  memorySize: 2048
  environment:
    NOTION_API_KEY: ${env:NOTION_API_KEY}
    NOTION_DATABASE_ID: ${env:NOTION_DATABASE_ID}
    CHROME_AWS_LAMBDA_CACHE_DIR: /tmp
    CHROMIUM_PATH: '/opt/nodejs/node_modules/@sparticuz/chromium/bin/chromium'  # Lambdaレイヤーでのパス
  apiGateway:
    timeout: 29

functions:
  createUGC:
    handler: handler.createUGC
    events:
      - http:
          path: /create-ugc
          method: post
          cors:
            origin: '*'
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false
    timeout: 30 # API Gatewayに接続していると、30秒までに制限されます
    memorySize: 2048  # メモリサイズを増やして処理速度を改善 4096
    # layers:
    #   - arn:aws:lambda:ap-northeast-1:045346784959:layer:sparticuz-chrome:4 # 24/12/05 指定しなくても動作した。Lambda関数のレイヤーに追加も不要でした。

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: webpack.config.js
    includeModules:
      packagePath: './package.json'
    packagerOptions:
      scripts:
        - rm -rf node_modules/puppeteer/.local-chromium
    excludeFiles:
      - .webpack/**
      - .serverless/**
  serverless-offline:
    httpPort: 5002
    noPrependStageInUrl: true

package:
  individually: true
